package generate

import (
	"fmt"
	"strings"

	"github.com/sysrqio/liegenpulse/internal/config"
)

func Telegraf(root *config.Root) string {
	var b strings.Builder
	b.WriteString("# Generated by liegenpulse — Telegraf inputs snippet\n")
	b.WriteString("# https://github.com/sysrqio/liegenpulse\n\n")

	modbus := []struct {
		building string
		meter    config.Meter
	}{}
	mqtt := []struct {
		building string
		meter    config.Meter
	}{}

	for _, bl := range root.Buildings {
		for _, m := range bl.Meters {
			switch m.Protocol {
			case config.ProtocolModbus:
				modbus = append(modbus, struct {
					building string
					meter    config.Meter
				}{bl.ID, m})
			case config.ProtocolMQTT:
				mqtt = append(mqtt, struct {
					building string
					meter    config.Meter
				}{bl.ID, m})
			}
		}
	}

	if len(modbus) > 0 {
		b.WriteString("[[inputs.modbus]]\n")
		b.WriteString("  name = \"liegenpulse_modbus\"\n")
		b.WriteString("  controller = \"tcp://127.0.0.1:502\"\n")
		b.WriteString("  configuration_type = \"register\"\n")
		b.WriteString("  tagexclude = [\"name\"]\n\n")
		for _, entry := range modbus {
			m := entry.meter
			fmt.Fprintf(&b, "  [inputs.modbus.tags]\n")
			fmt.Fprintf(&b, "    building = %q\n", entry.building)
			fmt.Fprintf(&b, "    meter_id = %q\n", m.ID)
			fmt.Fprintf(&b, "    meter_type = %q\n\n", m.Type)
			fmt.Fprintf(&b, "  [[inputs.modbus.request]]\n")
			fmt.Fprintf(&b, "    slave_id = 1\n")
			fmt.Fprintf(&b, "    byte_order = \"AB\"\n")
			fmt.Fprintf(&b, "    register = \"holding\"\n")
			fmt.Fprintf(&b, "    fields = [{name=\"energy_kwh\", address=0, type=\"FLOAT32\"}]\n")
			fmt.Fprintf(&b, "    # address from config: %s\n\n", m.Address)
		}
	}

	if len(mqtt) > 0 {
		b.WriteString("[[inputs.mqtt_consumer]]\n")
		b.WriteString("  servers = [\"tcp://127.0.0.1:1883\"]\n")
		b.WriteString("  topics = [\n")
		for i, entry := range mqtt {
			comma := ","
			if i == len(mqtt)-1 {
				comma = ""
			}
			fmt.Fprintf(&b, "    %q%s\n", entry.meter.Topic, comma)
		}
		b.WriteString("  ]\n")
		b.WriteString("  data_format = \"json\"\n")
		b.WriteString("  tag_keys = [\"building\", \"meter_id\", \"meter_type\"]\n\n")
		for _, entry := range mqtt {
			m := entry.meter
			fmt.Fprintf(&b, "  [[inputs.mqtt_consumer.topic_parsing]]\n")
			fmt.Fprintf(&b, "    topic = %q\n", m.Topic)
			fmt.Fprintf(&b, "    tags = { building = %q, meter_id = %q, meter_type = %q }\n\n",
				entry.building, m.ID, m.Type)
		}
	}

	return b.String()
}
